"""Update Grant model with new fields

Revision ID: 0096c541c2f6
Revises: ec99581bebde
Create Date: 2025-06-16 02:36:50.872968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0096c541c2f6'
down_revision = 'ec99581bebde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('agency', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('grant_number', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('proposal_due_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('award_date', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint(None, ['grant_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grant', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('award_date')
        batch_op.drop_column('proposal_due_date')
        batch_op.drop_column('grant_number')
        batch_op.drop_column('agency')

    # ### end Alembic commands ###
