"""Update ComputeResource model with new fields

Revision ID: ec99581bebde
Revises: 3cf921de8f2b
Create Date: 2025-06-16 02:34:54.667659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec99581bebde'
down_revision = '3cf921de8f2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compute_resource', schema=None) as batch_op:
        batch_op.add_column(sa.Column('specification', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('status', sa.Enum('AVAILABLE', 'IN_USE', 'MAINTENANCE', 'RETIRED', name='computeresourcestatus'), nullable=False))
        batch_op.add_column(sa.Column('cluster_type', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('nodes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cpus_per_node', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('gpus_per_node', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('memory_per_node', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('storage_per_node', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('network_bandwidth', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compute_resource', schema=None) as batch_op:
        batch_op.drop_column('network_bandwidth')
        batch_op.drop_column('storage_per_node')
        batch_op.drop_column('memory_per_node')
        batch_op.drop_column('gpus_per_node')
        batch_op.drop_column('cpus_per_node')
        batch_op.drop_column('nodes')
        batch_op.drop_column('cluster_type')
        batch_op.drop_column('status')
        batch_op.drop_column('specification')

    # ### end Alembic commands ###
